### PR TITLE
clarify optional blackjack simulation

### PR DESCRIPTION
**Pull request by mullaney**

### CODE REVIEW

**Comment by wmleidy** [comment]
I think this is misleading. The code should be able to simulate game flow whether it is a junior, mid, or senior submission.

**Comment by wmleidy** [comment]
I think the part optional is whether player strategy should be simulated.

**Comment by wmleidy** [comment]
@mullaney Do you agree? If so, I will open a pull.

**Comment by mullaney** [comment]
@wmleidy I never interpreted that way. I always thought the entire bullet point below 'Optional' was optional.

**Pull request merged**
